### ISSUE TITLE
No logs even after a few minutes

### ISSUE THREAD

**Issue by takara2314** [approvers/devoirs-core#10]
Hello.
I executed ``node index`` in ``/example/``, but I couldn't see logs, such as course names and assignments names, after a few minutes. In addition, the console didn't show the error logs.

## Done list before executing ``node index``
- Changed used devoirs-core version, ``..`` to ``~0.2.1`` at ``/example/package.json``
- Executed ``npm install`` in ``/example/``
- Set the correct value for enviroment variables, ``MICROSOFT_EMAIL`` and ``MICROSOFT_PASSWORD``

## Platform
- Ubuntu 20.04 LTS
- Node.js v15.5.1

**Comment by takara2314** [comment]
@siketyan Please confirm

**Comment by siketyan** [comment]
@takara2314 Thanks for reporting.
We confirmed the issue, occured because of the recent changes of the authorizing specification for OneNote API in Teams.
Also we resolved it by #11, and released v0.2.2.
https://github.com/approvers/devoirs-core/releases/tag/0.2.2

Could you try with the latest version?
Feel free to ask any other questions!

**Comment by siketyan** [comment]
Note that we recommended to require by `~0.2.2` or `^0.2.2`, rather than only upgrading the package in the lock file (It may occurs the issue again, when someone ignore the lock).

**Comment by takara2314** [comment]
@siketyan Thank you for fixing.
Trying with v0.2.2, I'm able to confirmed that the console outputs logs, such as course names and assignments names.

However, the following error has occurred when execute ``node index`` again.
```
/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for selector `input[type="email"]` failed: timeout 30000ms exceeded
    at new WaitTask (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    at Frame.waitForSelector (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    at Automator.type (/home/takara2314/devoirs-core/example/node_modules/devoirs-core/dist/services/authorizer/automatic.js:28:14)
    at Automator.login (/home/takara2314/devoirs-core/example/node_modules/devoirs-core/dist/services/authorizer/automatic.js:11:20)
    at /home/takara2314/devoirs-core/example/node_modules/devoirs-core/dist/services/authorizer/automatic.js:46:22
    at /home/takara2314/devoirs-core/example/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
```

For your reference, I've checked that the above error don't occurred when execute ``node index`` after delete generated ``/data/``.

**Comment by siketyan** [comment]
@takara2314
It seems an issue of re-authorization of the API.
And it is also an example issue, I think, because the ITokenProvider implementation does not store the access token.
Microsoft Teams app tries to re-authorize if the token unavailable, but if available it continues to the app screen.
Thus, if the token is still available, we need to provide the stored one via the provider.
Note that the token is available for about 1 hour, so after the time, the current implementation will works fine.

To keep the example simple, we do not use any filesystem for saving the token, excepting the Chromium data directory.
We are trying to fetch the access token from the Chromium data, if available, then use it instead of the provided one.

**Comment by takara2314** [comment]
@siketyan I see. Thank you for your reply.
